/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesAtsOptimizationRouteImport } from './routes/guides.ats-optimization'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedResumeAnalyzerRouteImport } from './routes/_authenticated/resume-analyzer'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'
import { Route as AuthenticatedLearningRoadmapRouteImport } from './routes/_authenticated/learning-roadmap'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationTrackerRouteImport } from './routes/_authenticated/application-tracker'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAtsOptimizationRoute = GuidesAtsOptimizationRouteImport.update({
  id: '/guides/ats-optimization',
  path: '/guides/ats-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeAnalyzerRoute =
  AuthenticatedResumeAnalyzerRouteImport.update({
    id: '/resume-analyzer',
    path: '/resume-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningRoadmapRoute =
  AuthenticatedLearningRoadmapRouteImport.update({
    id: '/learning-roadmap',
    path: '/learning-roadmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationTrackerRoute =
  AuthenticatedApplicationTrackerRouteImport.update({
    id: '/application-tracker',
    path: '/application-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/application-tracker': typeof AuthenticatedApplicationTrackerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning-roadmap': typeof AuthenticatedLearningRoadmapRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/resume-analyzer': typeof AuthenticatedResumeAnalyzerRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/guides/ats-optimization': typeof GuidesAtsOptimizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/application-tracker': typeof AuthenticatedApplicationTrackerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning-roadmap': typeof AuthenticatedLearningRoadmapRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/resume-analyzer': typeof AuthenticatedResumeAnalyzerRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/guides/ats-optimization': typeof GuidesAtsOptimizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/application-tracker': typeof AuthenticatedApplicationTrackerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learning-roadmap': typeof AuthenticatedLearningRoadmapRoute
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/resume-analyzer': typeof AuthenticatedResumeAnalyzerRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/guides/ats-optimization': typeof GuidesAtsOptimizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/application-tracker'
    | '/dashboard'
    | '/learning-roadmap'
    | '/mock-interview'
    | '/resume-analyzer'
    | '/security'
    | '/settings'
    | '/guides/ats-optimization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/application-tracker'
    | '/dashboard'
    | '/learning-roadmap'
    | '/mock-interview'
    | '/resume-analyzer'
    | '/security'
    | '/settings'
    | '/guides/ats-optimization'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/application-tracker'
    | '/_authenticated/dashboard'
    | '/_authenticated/learning-roadmap'
    | '/_authenticated/mock-interview'
    | '/_authenticated/resume-analyzer'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/guides/ats-optimization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesAtsOptimizationRoute: typeof GuidesAtsOptimizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/ats-optimization': {
      id: '/guides/ats-optimization'
      path: '/guides/ats-optimization'
      fullPath: '/guides/ats-optimization'
      preLoaderRoute: typeof GuidesAtsOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-analyzer': {
      id: '/_authenticated/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof AuthenticatedResumeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-roadmap': {
      id: '/_authenticated/learning-roadmap'
      path: '/learning-roadmap'
      fullPath: '/learning-roadmap'
      preLoaderRoute: typeof AuthenticatedLearningRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/application-tracker': {
      id: '/_authenticated/application-tracker'
      path: '/application-tracker'
      fullPath: '/application-tracker'
      preLoaderRoute: typeof AuthenticatedApplicationTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationTrackerRoute: typeof AuthenticatedApplicationTrackerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearningRoadmapRoute: typeof AuthenticatedLearningRoadmapRoute
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedResumeAnalyzerRoute: typeof AuthenticatedResumeAnalyzerRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationTrackerRoute: AuthenticatedApplicationTrackerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearningRoadmapRoute: AuthenticatedLearningRoadmapRoute,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedResumeAnalyzerRoute: AuthenticatedResumeAnalyzerRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesAtsOptimizationRoute: GuidesAtsOptimizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
